---
title: "GRÓ-FTP ARAM - Population Models"
---

## Prerequisites

For this part of the GRO-FTP ARAM line, you are expected to already have some fluency in using Rstudio and tidyverse. At this point you should also start thinking of how you plan to organize your files and work into a project, or even start using Rmarkdown files to take notes and do exploratory studies and plots.

## Schedule

The population dynamics section of teaching is split into roughly 8 half-day sessions:

[Simple population models](Simple_population_models.qmd)

[Review-what are models?](Review-what%20are%20models.qmd)

[Fitting a logistic growth curve](Fitting_logistic_curve.qmd)

[Surplus production models](Surplus_production_models.qmd)

\[SPICT exercise\]

\[Components of an age-based model 1\](

\[Components of an age-based model 2\]

\[Age-based models 1\]

\[Age-based models 2\]

Uploading material the first time

navigate to

cd /net/hafri/export/home/hafri/pamela/public_html

copy

cp -a \~/Documents/Hafro/UNU/2024/PopModels/\_site .

move

mv \_site population_dynamics

permissions

chmod 777 population_dynamics

check

ls -l

RE-uploading material

Render here, check index.html

rm -r population_dynamics/

cp -a \~/Documents/Hafro/UNU/2024/PopModels/\_site .

mv \_site population_dynamics

chmod 777 population_dynamics

ls -l

heima..
